name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: CLIGameControllerTest
      id: cligamecontrollertest
      uses: education/autograding-command-grader@v1
      with:
        test-name: CLIGameControllerTest
        setup-command: mvn compile
        command: mvn -Dtest=CLIControllerTest test
        timeout: 3
        max-score: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        CLIGAMECONTROLLERTEST_RESULTS: "${{steps.cligamecontrollertest.outputs.result}}"
      with:
        runners: cligamecontrollertest
